version: "3.9"
services:
    web:
      build: .
      ports:
      - 5000:5000
    redis:
      image: "redis:alpine"
    client:
      image: "yoavklein3/net-tools:0.2"
      command: ["sleep", "3600"]
