version: "3.9"
services:
    web:
      build: .
      ports:
      - 5000:5000
      container_name: webos
    redis:
      image: "redis:alpine"
      container_name: myredis
    client:
      image: "yoavklein3/net-tools:0.2"
      command: ["sleep", "3600"]
      container_name: client
